INSERT INTO `COUNTRY` (`ID`, `COUNTRYNAME`,`ARCHIVED`,`COUNTRYCODE`) VALUES (1, 'USA',0,'US');
INSERT INTO `COUNTRY` (`ID`, `COUNTRYNAME`,`ARCHIVED`,`COUNTRYCODE`) VALUES (2, 'INDIA',0,'IN');
INSERT INTO `COUNTRY` (`ID`, `COUNTRYNAME`,`ARCHIVED`,`COUNTRYCODE`) VALUES (3, 'ITALY',0,'IT');


INSERT INTO `STATE` (`ID`,`STATECODE`, `STATENAME`, `ARCHIVED`,`COUNTRYID`) VALUES
(1, 'AL', 'Alabama',false,1),
(2, 'AK', 'Alaska',false,1),
(3, 'AZ', 'Arizona',false,1),
(4, 'AR', 'Arkansas',false,1),
(5, 'CA', 'California',false,1),
(6, 'CO', 'Colorado',false,1),
(7, 'CT', 'Connecticut',false,1),
(8, 'DE', 'Delaware',false,1),
(9, 'DC', 'District of Columbia',false,1),
(10, 'FL', 'Florida',false,1),
(11, 'GA', 'Georgia',false,1),
(12, 'HI', 'Hawaii',false,1),
(13, 'ID', 'Idaho',false,1),
(14, 'IL', 'Illinois',false,1),
(15, 'IN', 'Indiana',false,1),
(16, 'IA', 'Iowa',false,1),
(17, 'KS', 'Kansas',false,1),
(18, 'KY', 'Kentucky',false,1),
(19, 'LA', 'Louisiana',false,1),
(20, 'ME', 'Maine',false,1),
(21, 'MD', 'Maryland',false,1),
(22, 'MA', 'Massachusetts',false,1),
(23, 'MI', 'Michigan',false,1),
(24, 'MN', 'Minnesota',false,1),
(25, 'MS', 'Mississippi',false,1),
(26, 'MO', 'Missouri',false,1),
(27, 'MT', 'Montana',false,1),
(28, 'NE', 'Nebraska',false,1),
(29, 'NV', 'Nevada',false,1),
(30, 'NH', 'New Hampshire',false,1),
(31, 'NJ', 'New Jersey',false,1),
(32, 'NM', 'New Mexico',false,1),
(33, 'NY', 'New York',false,1),
(34, 'NC', 'North Carolina',false,1),
(35, 'ND', 'North Dakota',false,1),
(36, 'OH', 'Ohio',false,1),
(37, 'OK', 'Oklahoma',false,1),
(38, 'OR', 'Oregon',false,1),
(39, 'PA', 'Pennsylvania',false,1),
(40, 'RI', 'Rhode Island',false,1),
(41, 'SC', 'South Carolina',false,1),
(42, 'SD', 'South Dakota',false,1),
(43, 'TN', 'Tennessee',false,1),
(44, 'TX', 'Texas',false,1),
(45, 'UT', 'Utah',false,1),
(46, 'VT', 'Vermont',false,1),
(47, 'VA', 'Virginia',false,1),
(48, 'WA', 'Washington',false,1),
(49, 'WV', 'West Virginia',false,1),
(50, 'WI', 'Wisconsin',false,1),
(51, 'WY', 'Wyoming',false,1);

INSERT INTO `STATE` (`ID`,`STATECODE`, `STATENAME`, `ARCHIVED`,`COUNTRYID`) VALUES
(52, 'AN', 'Andaman and Nicoba',false,2),
(53, 'AP', 'Andhra Pradesh',false,2),
(54, 'AR', 'Arunachal Pradesh',false,2),
(55, 'AS', 'Assam',false,2),
(56, 'BR', 'Bihar',false,2),
(57, 'CH', 'Chandigarh',false,2),
(58, 'CG', 'Chhattisgarh',false,2),
(59, 'DN', 'Dadra and Nagar Haveli',false,2),
(60, 'DD', 'Daman and Diu',false,2),
(61, 'DL', 'Delhi',false,2),
(62, 'GA', 'Goa',false,2),
(63, 'GJ', 'Gujarat',false,2),
(64, 'HR', 'Haryana',false,2),
(65, 'HP', 'Himachal Pradesh',false,2),
(66, 'JK', 'Jammu and Kashmir',false,2),
(67, 'JH', 'Jharkhand',false,2),
(68, 'KA', 'Karnataka',false,2),
(69, 'KL', 'Kerala',false,2),
(70, 'LD', 'Lakshadweep',false,2),
(71, 'MP', 'Madhya Pradesh',false,2),
(72, 'MH', 'Maharashtra',false,2),
(73, 'MN', 'Manipur',false,2),
(74, 'ML', 'Meghalaya',false,2),
(75, 'MZ', 'Mizoram',false,2),
(76, 'NL', 'Nagaland',false,2),
(77, 'OD', 'Odisha',false,2),
(78, 'PY', 'Puducherry',false,2),
(79, 'PB', 'Punjab',false,2),
(80, 'RJ', 'Rajasthan',false,2),
(81, 'SK', 'Sikkim',false,2),
(82, 'TN', 'Tamil Nadu',false,2),
(83, 'TS', 'Telangana',false,2),
(84, 'TR', 'Tripura',false,2),
(85, 'UK', 'Uttarakhand',false,2),
(86, 'UP', 'Uttar Pradesh',false,2),
(87, 'WB', 'West Bengal',false,2);
INSERT INTO `STATE` (`ID`,`STATECODE`, `STATENAME`, `ARCHIVED`,`COUNTRYID`) VALUES
(88, 'AG', 'Agrigento',false,3),
(89, 'AL', 'Alessandria',false,3),
(90, 'AN', 'Ancona',false,3),
(91, 'AO', 'Aosta',false,3),
(92, 'AR', 'Arezzo',false,3),
(93, 'AP', 'Ascoli Piceno',false,3),
(94, 'AT', 'Asti',false,3),
(95, 'AV', 'Avellino',false,3),
(96, 'BA', 'Bari',false,3),
(97, 'BL', 'Belluno',false,3),
(98, 'BN', 'Benevento',false,3),
(99, 'BG', 'Bergamo',false,3),
(100, 'BI', 'Biella',false,3),
(101, 'BO', 'Bologna',false,3),
(102, 'BZ', 'Bolzano',false,3),
(103, 'BS', 'Brescia',false,3),
(104, 'BR', 'Brindisi',false,3),
(105, 'CA', 'Cagliari',false,3),
(106, 'CL', 'Caltanissetta',false,3),
(107, 'CB', 'Campobasso',false,3),
(108, 'CE', 'Caserta',false,3),
(109, 'CT', 'Catania',false,3),
(110, 'CZ', 'Catanzaro',false,3),
(111, 'CH', 'Chieti',false,3),
(112, 'CO', 'Como',false,3),
(113, 'CS', 'Cosenza',false,3),
(114, 'CR', 'Cremona',false,3),
(115, 'KR', 'Crotone',false,3),
(116, 'CN', 'Cuneo',false,3),
(117, 'EN', 'Enna',false,3),
(118, 'FE', 'Ferrara',false,3),
(119, 'FI', 'Firenze',false,3),
(120, 'FG', 'Foggia',false,3),
(121, 'FO', 'Forli-Cesena',false,3),
(122, 'FR', 'Frosinone',false,3),
(123, 'GE', 'Genova',false,3),
(124, 'GO', 'Gorizia',false,3),
(125, 'GR', 'Grosseto',false,3),
(126, 'IM', 'Imperia',false,3),
(127, 'IS', 'Isernia',false,3),
(128, 'SP', 'La Spezia',false,3),
(129, 'AQ', 'L Aquila',false,3),
(130, 'LT', 'Latina',false,3),
(131, 'LE', 'Lecce',false,3),
(132, 'LO', 'Lecco',false,3),
(133, 'LI', 'Livorno',false,3),
(134, 'LO', 'Lodi',false,3),
(135, 'LU', 'Lucca',false,3),
(136, 'MC', 'Macerata',false,3),
(137, 'MN', 'Mantova',false,3),
(138, 'MS', 'Massa-Carrara',false,3),
(139, 'MT', 'Matera',false,3),
(140, 'ME', 'Messina',false,3),
(141, 'MI', 'Milano',false,3),
(142, 'MO', 'Modena',false,3),
(143, 'MB', 'Monza e Brianza',false,3),
(144, 'NA', 'Napoli',false,3),
(145, 'NO', 'Novara',false,3),
(146, 'NU', 'Nuoro',false,3),
(147, 'OR', 'Oristano',false,3),
(148, 'PD', 'Padova',false,3),
(149, 'PA', 'Palermo',false,3),
(150, 'PR', 'Parma',false,3),
(151, 'PV', 'Pavia',false,3),
(152, 'PG', 'Perugia',false,3),
(153, 'PS', 'Pesaro',false,3),
(154, 'PE', 'Pescara',false,3),
(155, 'PC', 'Piacenza',false,3),
(156, 'PI', 'Pisa',false,3),
(157, 'PT', 'Pistoia',false,3),
(158, 'PN', 'Pordenone',false,3),
(159, 'PZ', 'Potenza',false,3),
(160, 'PO', 'Prato',false,3),
(161, 'RG', 'Ragusa',false,3),
(162, 'RA', 'Ravenna',false,3),
(163, 'RC', 'Reggio Calabria',false,3),
(164, 'RE', 'Reggio Emilia',false,3),
(165, 'RI', 'Rieti',false,3),
(167, 'RN', 'Rimini',false,3),
(168, 'RM', 'Roma',false,3),
(169, 'RO', 'Rovigo',false,3),
(170, 'SA', 'Salerno',false,3),
(171, 'SS', 'Sassari',false,3),
(172, 'SV', 'Savona',false,3),
(173, 'SI', 'Siena',false,3),
(174, 'SR', 'Siracusa',false,3),
(175, 'SO', 'Sondrio',false,3),
(176, 'TA', 'Taranto',false,3),
(177, 'TE', 'Teramo',false,3),
(178, 'TR', 'Terni',false,3),
(179, 'TO', 'Torino',false,3),
(180, 'TP', 'Trapani',false,3),
(181, 'TN', 'Trento',false,3),
(182, 'TV', 'Treviso',false,3),
(183, 'TS', 'Trieste',false,3),
(184, 'UD', 'Udine',false,3),
(185, 'VA', 'Varese',false,3),
(186, 'VB', 'Verbania-Cusio-Ossola',false,3),
(187, 'VC', 'Vercelli',false,3),
(188, 'VR', 'Verona',false,3),
(189, 'VV', 'Vibo Valentia',false,3),
(190, 'VI', 'Vicenza',false,3),
(191, 'VT', 'Viterbo',false,3);