/*Takeoff permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('takeoff_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('takeoff_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('takeoff_u',0,1,CURRENT_TIMESTAMP,NULL,'Update',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('takeoff_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('takeoff_login_email',0,1,CURRENT_TIMESTAMP,NULL,'Login Email',NULL,1);
/*Takeoff permission end*/

/*Quote permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('quote_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('quote_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('quote_u',0,1,CURRENT_TIMESTAMP,NULL,'Update',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('quote_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('quote_follow',0,1,CURRENT_TIMESTAMP,NULL,'Follow/Email',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('quote_undead',0,1,CURRENT_TIMESTAMP,NULL,'Undead Quote',NULL,1);
/*Quote permission end*/

/*Job Order permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('joborder_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('joborder_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('joborder_u',0,1,CURRENT_TIMESTAMP,NULL,'Update/Final',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('joborder_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('joborder_rollback',0,1,CURRENT_TIMESTAMP,NULL,'Roll Back',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('joborder_remind',0,1,CURRENT_TIMESTAMP,NULL,'Remind',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('joborder_tax',0,1,CURRENT_TIMESTAMP,NULL,'Tax',NULL,1);
/*Job Order permission end*/

/*Order Book permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('orderbook_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('orderbook_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('orderbook_u',0,1,CURRENT_TIMESTAMP,NULL,'Update',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('orderbook_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('orderbook_ship',0,1,CURRENT_TIMESTAMP,NULL,'Ship To',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('orderbook_orbf',0,1,CURRENT_TIMESTAMP,NULL,'ORBF',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('orderbook_remind',0,1,CURRENT_TIMESTAMP,NULL,'Est Remind',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('orderbook_change',0,1,CURRENT_TIMESTAMP,NULL,'Change UC',NULL,1);
/*Order Book permission end*/

/*AW permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('aw_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('aw_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('aw_u',0,1,CURRENT_TIMESTAMP,NULL,'Update',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('aw_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('aw_remind',0,1,CURRENT_TIMESTAMP,NULL,'Low Inv Remind',NULL,1);
/*AW permission end*/

/*AWF permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('awf_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('awf_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('awf_u',0,1,CURRENT_TIMESTAMP,NULL,'Update',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('awf_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('awf_remind',0,1,CURRENT_TIMESTAMP,NULL,'Low Inv Remind',NULL,1);
/*AWF permission end*/

/*SBC permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('sbc_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('sbc_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('sbc_u',0,1,CURRENT_TIMESTAMP,NULL,'Update',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('sbc_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('sbc_remind',0,1,CURRENT_TIMESTAMP,NULL,'Low Inv Remind',NULL,1);
/*SBC permission end*/

/*SPL permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('spl_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('spl_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('spl_u',0,1,CURRENT_TIMESTAMP,NULL,'Update',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('spl_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('spl_remind',0,1,CURRENT_TIMESTAMP,NULL,'Low Inv Remind',NULL,1);
/*SPL permission end*/

/*JOB permission begin*/
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('job_c',0,1,CURRENT_TIMESTAMP,NULL,'Create/Add',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('job_r',0,1,CURRENT_TIMESTAMP,NULL,'Read/View/Search',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('job_u',0,1,CURRENT_TIMESTAMP,NULL,'Update',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('job_d',0,1,CURRENT_TIMESTAMP,NULL,'Delete',NULL,1);
INSERT INTO `awacp`.`permission`(`AUTHORITY`,`ARCHIVED`,`CREATEDBYID`,`DATECREATED`,`DATEUPDATED`,`DESCRIPTION`,`UPDATEDBYID`,`VERSION`)
VALUES('job_remind',0,1,CURRENT_TIMESTAMP,NULL,'Low Inv Remind',NULL,1);
/*JOB permission end*/